# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_auto_20171121_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_round', models.IntegerField()),
                ('status', models.CharField(choices=[('Not Scheduled', 'Not Scheduled'), ('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Not Scheduled', max_length=20)),
                ('winner', models.CharField(blank=True, choices=[('Player 1', 'Player 1'), ('Player 2', 'Player 2')], max_length=20)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixture.Fixture')),
                ('left_previous', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_childs', to='fixture.Match')),
                ('player_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_matches', to='fixture.Player')),
                ('player_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_matches', to='fixture.Player')),
                ('right_previous', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_childs', to='fixture.Match')),
                ('winning_palyer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='fixture.Player')),
            ],
        ),
    ]
