# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
