# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0004_match_match_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winning_palyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='fixture.Player'),
        ),
    ]
