# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0005_auto_20171121_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='left_previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_childs', to='fixture.Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_matches', to='fixture.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_matches', to='fixture.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='right_previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_childs', to='fixture.Match'),
        ),
    ]
