# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0006_auto_20171121_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fixture.Fixture'),
        ),
    ]
