# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0006_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True, verbose_name='Match Date'),
        ),
    ]
