# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0007_auto_20171121_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='left_previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_next_match', to='fixture.Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='right_previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_next_match', to='fixture.Match'),
        ),
    ]
