# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0010_fixture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
