# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0011_auto_20171122_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 7, 8, 27, 672522), verbose_name='date published'),
        ),
    ]
