# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0012_fixture_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
