# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0013_auto_20171122_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixturePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='players',
        ),
        migrations.AddField(
            model_name='fixtureplayer',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fixture.Fixture'),
        ),
        migrations.AddField(
            model_name='fixtureplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_in_fixture', to='fixture.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='fixtureplayer',
            unique_together=set([('rank', 'fixture')]),
        ),
    ]
