# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0014_auto_20171122_1352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixtureplayer',
            unique_together=set([('fixture', 'player'), ('rank', 'fixture')]),
        ),
    ]
