# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0015_auto_20171123_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
