# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0016_auto_20171123_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, upload_to='icons/%Y/%m/%d/')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='fixture.Fixture')),
            ],
        ),
    ]
