# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0017_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
