# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0018_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='description',
        ),
        migrations.AddField(
            model_name='display',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
