# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0019_auto_20171123_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
